### PR TITLE
Fix #224: Tolerate incorrect page when ignoreMissingPage is enabled

### LINKED ISSUE #224: Don't throw exception when `BaseListView::$ignoreMissingPage` is `true` and passed negative page value

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

File: src/BaseListView.php [hunk 1]
```diff
@@ -342,11 +343,10 @@ private function prepareDataReaderAndGetItems(array $filters): array
             $this->urlConfig->getSortParameterType(),
         );
 
-        $this->preparedDataReader = $this->prepareDataReaderByParams($page, $previousPage, $pageSize, $sort, $filters);
-
         try {
+            $this->preparedDataReader = $this->prepareDataReaderByParams($page, $previousPage, $pageSize, $sort, $filters);
             return $this->getItems($this->preparedDataReader);
-        } catch (PageNotFoundException $exception) {
+        } catch (PageNotFoundException|PaginatorException $exception) {
```
Comment (vjik) [inline src/BaseListView.php:349]: `pageNotFoundExceptionCallback` work with `PageNotFoundException` and don't support `PaginatorException`. It needs to resolve.

**Review by vjik — CHANGES_REQUESTED** [review]

**Review by vjik — APPROVED** [review]
